services:
  # データベース（PostgreSQL）
  db:
    image: postgres:15-alpine
    container_name: blog-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      # - ./db_data:/var/lib/postgresql/data # データをPCに残す設定

  # バックエンド（Go / Gin）
  api:
    build: ./backend
    container_name: blog-api
    ports:
      - "8888:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: blog_db