// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"my-blog-backend/controller"
	"my-blog-backend/infra"
	"my-blog-backend/usecase"
)

// Injectors from wire.go:

func InitAuthController(db *sql.DB) controller.AuthController {
	authRepository := infra.NewAuthRepository(db)
	authUseCase := usecase.NewAuthUseCase(authRepository)
	authController := controller.NewAuthController(authUseCase)
	return authController
}

func InitAuthUseCase(conn *sql.DB) usecase.AuthUseCase {
	authRepository := infra.NewAuthRepository(conn)
	authUseCase := usecase.NewAuthUseCase(authRepository)
	return authUseCase
}

func InitPostController(db *sql.DB) controller.PostController {
	postRepository := infra.NewPostRepository(db)
	postUseCase := usecase.NewPostUseCase(postRepository)
	postController := controller.NewPostController(postUseCase)
	return postController
}
